### ISSUE TITLE
Ревью #1

### ISSUE THREAD

**Issue by ShkiTTer** [Egor-Ruban/Novella#1]
1. В разметке ID элементов должны быть в стиле `camelCase`, а не `snake_case`
2. Для полей ввода нужно указывать `inputType`, чтобы открывалась правильная клавиатура.
https://github.com/Egor-Ruban/Novella/blob/c2fc462e662a6b73b4da12b2e9e730bd59831fd6/app/src/main/res/layout/activity_introduction.xml#L52-L70

3. Переменные стоит объявлять внутри класса. В других активити аналогично
https://github.com/Egor-Ruban/Novella/blob/c2fc462e662a6b73b4da12b2e9e730bd59831fd6/app/src/main/java/com/example/novella/MainActivity.kt#L8

4. Название ключей нужно выносить в константы, чтобы избежать опечаток и ошибок. Да и понятнее сразу станет.
https://github.com/Egor-Ruban/Novella/blob/c2fc462e662a6b73b4da12b2e9e730bd59831fd6/app/src/main/java/com/example/novella/IntroActivity.kt#L18

5. Что-то мне подсказывает, что тут должна быть проверка, чтобы пользователь не мог начать играть без ввода имени
https://github.com/Egor-Ruban/Novella/blob/c2fc462e662a6b73b4da12b2e9e730bd59831fd6/app/src/main/java/com/example/novella/IntroActivity.kt#L20

6. Строка по умолчанию должна быть в файле со строками
https://github.com/Egor-Ruban/Novella/blob/c2fc462e662a6b73b4da12b2e9e730bd59831fd6/app/src/main/java/com/example/novella/StoryActivity.kt#L20

7. Для работы с `JSON`, а именно парсинга, я бы использовал либо `Gson`, либо `Kotlin Serialization`. Так у тебя будут компактные модели, не будет кучи строковых ключей в коде и в целом код сократится и станет более понятным.
Если не хочешь их использовать в этой лабе, то можно оставить стандартный `JsonObject`, но тогда названия всех ключей нужно вынести в константы.

8. Конструкция мягко говоря странная и плохая. Если делаешь `JSON`, то делай его однотипным, чтобы все поля были. Значит в каждом блоке нужно добавить поле `showKir` и задавать его как `null`. Использование библиотеки для сериализации избавило бы от этой проблемы благодаря значениям по умолчанию в моделях данных.
https://github.com/Egor-Ruban/Novella/blob/c2fc462e662a6b73b4da12b2e9e730bd59831fd6/app/src/main/java/com/example/novella/StoryActivity.kt#L41-L47

9. Этот блок можно и стоит сделать проще.
https://github.com/Egor-Ruban/Novella/blob/c2fc462e662a6b73b4da12b2e9e730bd59831fd6/app/src/main/java/com/example/novella/StoryActivity.kt#L65-L69

```
val intent = if (jsonAnswer.getInt("nextID") != 14) {
    Intent(baseContext, StoryActivity::class.java)
         .putExtra("id", jsonAnswer.getInt("nextID"))
} else {
    Intent(baseContext, EndActivity::class.java)
}
```

10. Для последней сцены лучше в поле `nextID` записывать `null`. Так, если добавишь еще сцены не придется ничего переписывать. Да и проверки на какие-то магические константы в коде не будет
https://github.com/Egor-Ruban/Novella/blob/c2fc462e662a6b73b4da12b2e9e730bd59831fd6/app/src/main/java/com/example/novella/StoryActivity.kt#L66

11. Не используй подобные названия для переменных. Вообще не понятно, что это и для чего. Придумывай осознанные названия, которые описывают суть переменной, что в ней лежит или для чего она.
https://github.com/Egor-Ruban/Novella/blob/c2fc462e662a6b73b4da12b2e9e730bd59831fd6/app/src/main/java/com/example/novella/StoryActivity.kt#L42

**Comment by Egor-Ruban** [comment]
1 - почему-то всегда в snake писал - исправил
2 - исправил
3 - бес попутал - исправил
4 - Где стоит хранить эту константу?
5 - добавил
6 - исправил
7 - Gson использовал  ранее, тут решил, что JSONObject с головой хватит. Опять же вопрос где хранить константы
8 - не красиво исправил, добавил поле во все объекты в JSON
9 - переделал
10 - JSONObject бросает ошибку если null, то есть аккуратно этот null не считать, поэтому сделал особый nextID, равный -1
(да, Gson сила)
11 - ну это любимое.- исправил
